name: mr_finance
services:

  # ── Node.js + vite ────────────────────────────────────────────────────────────────
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_app2
    volumes:
      - ./app:/app                   # código fuente en ./app del host
      - mrfinance_root_modules:/app/mrfinance/node_modules
      - mrfinance_server_modules:/app/mrfinance/server/node_modules
      - mrfinance_client_modules:/app/mrfinance/client/node_modules
    ports:
      - "587:587"
      - "3000:3000"
      - "5173:5173"
      - "8081:8081"
      # - "0.0.0.0:443:5173"
      # - "0.0.0.0:80:5173"
    environment:
      NODE_ENV: development
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: user
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev_net
    restart: no

  # ── Nginx ──────────────────────────────────────────────────────────────────
  nginx:
    image: jonasal/nginx-certbot:latest
    container_name: nginx_server
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CERTBOT_EMAIL=noreply.mrfinance@gmail.com
    volumes:
      - ./app/mrfinance/client/dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/user_conf.d/default.conf:ro
      - certbot_letsencrypt:/etc/letsencrypt
    depends_on:
      - app
    networks:
      - dev_net
    restart: no

  # ── MySQL ──────────────────────────────────────────────────────────────────
  db:
    image: mysql:latest
    container_name: mysql2
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: MrFinanceV2
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - dev_net
    restart: no

  # ── phpMyAdmin ─────────────────────────────────────────────────────────────
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyAdmin2
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      UPLOAD_LIMIT: 100M
    ports:
      - "8080:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - dev_net
    restart: no

# ── Volúmenes ─────────────────────────────────────────────────────────────────
volumes:
  mysql_data:
  mrfinance_root_modules:
  mrfinance_server_modules:
  mrfinance_client_modules:
  certbot_letsencrypt:

# ── Red interna ───────────────────────────────────────────────────────────────
networks:
  dev_net:
    driver: bridge
